# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UniversalAppDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
	pod 'ReachabilitySwift'
  pod 'SDWebImage', '~> 5.0'

  # Pods for UniversalAppDemo

  target 'UniversalAppDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UniversalAppDemoUITests' do
    # Pods for testing
  end

end
